// Generates docs/IMPLEMENTATION-STATUS.md -- the operator's "what is
// actually built" record -- from packages/conformance/src/matrix.mjs (the
// only machine-readable record of what is actually proved) plus the roadmap
// document at docs/analysis/32-PARITY-AND-FEATURE-MATRIX.md, read live via
// scripts/roadmap.mjs, for rows that have not landed a matrix row yet.
//
// State is derived, never asserted:
//   - a row with proof: null is UNPROVEN (matrix.mjs says why, in `note`);
//   - a row with browser: true is SHIPPED (browser-proved) -- its test only
//     runs in the CI browser job, or locally with MIROFY_CHROME set;
//   - any other row with a proof is SHIPPED.
// Rows the roadmap names that matrix.mjs does not yet carry are PLANNED --
// this is where every later P1b task's own row sits until its task lands,
// which is what keeps this file honest rather than aspirational.
//
// Run `npm run status` after any change to matrix.mjs (a task landing moves
// exactly one row from PLANNED to SHIPPED/UNPROVEN) or to the roadmap
// document. `npm run status:check` (wired into `npm run check`, immediately
// after check:changelog) regenerates into memory and diffs against the
// committed file, so a stale status file fails the build instead of quietly
// lying. Because both inputs are now read live from the tree, that diff
// covers the roadmap too: editing a roadmap row without rerunning
// `npm run status` fails the build.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { IMPORTED_ROWS } from '../packages/conformance/src/matrix.mjs';
import { ROADMAP_ROWS } from './roadmap.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..');
const OUT_PATH = path.join(repoRoot, 'docs/IMPLEMENTATION-STATUS.md');

const mdEscape = (value) => String(value)
  .replace(/\\/g, '\\\\')
  .replace(/\|/g, '\\|')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;');

function stateOf(row) {
  if (row.proof === null) return 'UNPROVEN';
  if (row.browser) return 'SHIPPED (browser-proved)';
  return 'SHIPPED';
}

const roadmapById = new Map(ROADMAP_ROWS.map(([id, name, origin, phase]) => [id, { name, origin, phase }]));
const matrixIds = new Set(IMPORTED_ROWS.map((row) => row.id));

function originOf(row) {
  return row.origin ?? roadmapById.get(row.id)?.origin ?? 'H';
}
function phaseOf(row) {
  return row.phase ?? roadmapById.get(row.id)?.phase ?? 'P0';
}

const shippedRows = IMPORTED_ROWS.filter((row) => row.proof !== null);
const browserProvedRows = shippedRows.filter((row) => row.browser);
const unprovenRows = IMPORTED_ROWS.filter((row) => row.proof === null);
const plannedRows = ROADMAP_ROWS.filter(([id]) => !matrixIds.has(id));

function render() {
  const lines = [];
  lines.push('# Implementation Status');
  lines.push('');
  lines.push('Generated by `node scripts/status.mjs` from `packages/conformance/src/matrix.mjs`');
  lines.push('(SHIPPED / UNPROVEN) and the roadmap document,');
  lines.push('`docs/analysis/32-PARITY-AND-FEATURE-MATRIX.md` (PLANNED -- rows the roadmap');
  lines.push('names that do not yet have a row of their own in the matrix).');
  lines.push('');
  lines.push('Do not hand-edit this file -- regenerate it with `npm run status`.');
  lines.push('`npm run status:check` (part of `npm run check`) fails the build if this file');
  lines.push('has drifted from what the matrix and the roadmap document would produce.');
  lines.push('');
  lines.push('PLANNED rows are read live from the roadmap document on every run, so they');
  lines.push('cannot silently disagree with it: edit a roadmap row without rerunning');
  lines.push('`npm run status` and the build fails.');
  lines.push('');
  lines.push(
    `**Totals:** ${shippedRows.length} SHIPPED (${browserProvedRows.length} browser-proved), `
    + `${unprovenRows.length} UNPROVEN, ${plannedRows.length} PLANNED.`,
  );
  lines.push('');
  lines.push('## Shipped & unproven — from the conformance matrix');
  lines.push('');
  lines.push('| ID | Name | Origin | Phase | State | Proof |');
  lines.push('|---|---|---|---|---|---|');
  for (const row of IMPORTED_ROWS) {
    const proof = row.proof === null ? `_none — ${mdEscape(row.note || 'no assertion exists')}_` : `\`${mdEscape(row.proof)}\``;
    lines.push(
      `| ${mdEscape(row.id)} | ${mdEscape(row.name)} | ${mdEscape(originOf(row))} | ${mdEscape(phaseOf(row))} `
      + `| ${stateOf(row)} | ${proof} |`,
    );
  }
  lines.push('');
  lines.push('## Planned — named in the roadmap, not yet in the matrix');
  lines.push('');
  lines.push('| ID | Name | Origin | Phase |');
  lines.push('|---|---|---|---|');
  for (const [id, name, origin, phase] of plannedRows) {
    lines.push(`| ${mdEscape(id)} | ${mdEscape(name)} | ${mdEscape(origin)} | ${mdEscape(phase)} |`);
  }
  lines.push('');
  return lines.join('\n');
}

const generated = render();

if (process.argv.includes('--check')) {
  let committed;
  try {
    committed = fs.readFileSync(OUT_PATH, 'utf8');
  } catch {
    console.error(`status:check: ${path.relative(repoRoot, OUT_PATH)} does not exist. Run \`npm run status\`.`);
    process.exit(1);
  }
  if (committed === generated) {
    console.log(`status:check: ${path.relative(repoRoot, OUT_PATH)} is up to date.`);
    process.exit(0);
  }
  console.error(`status:check: ${path.relative(repoRoot, OUT_PATH)} is stale -- committed content does not match what scripts/status.mjs would generate.`);
  const committedLines = committed.split('\n');
  const generatedLines = generated.split('\n');
  const limit = Math.max(committedLines.length, generatedLines.length);
  for (let i = 0; i < limit; i += 1) {
    if (committedLines[i] !== generatedLines[i]) {
      console.error(`  first difference at line ${i + 1}:`);
      console.error(`    committed:  ${JSON.stringify(committedLines[i] ?? '<eof>')}`);
      console.error(`    regenerated: ${JSON.stringify(generatedLines[i] ?? '<eof>')}`);
      break;
    }
  }
  console.error('Run `npm run status` to regenerate.');
  process.exit(1);
}

fs.writeFileSync(OUT_PATH, generated);
console.log(`status: wrote ${path.relative(repoRoot, OUT_PATH)} (${shippedRows.length} shipped, ${unprovenRows.length} unproven, ${plannedRows.length} planned)`);
