// Generates docs/IMPLEMENTATION-STATUS.md -- the operator's "what is
// actually built" record -- from packages/conformance/src/matrix.mjs (the
// only machine-readable record of what is actually proved) plus
// ROADMAP_SNAPSHOT (a committed, point-in-time copy of the sibling
// archify repo's roadmap; see scripts/roadmap-snapshot.mjs) for rows that
// have not landed a matrix row yet.
//
// State is derived, never asserted:
//   - a row with proof: null is UNPROVEN (matrix.mjs says why, in `note`);
//   - a row with browser: true is SHIPPED (browser-proved) -- its test only
//     runs in the CI browser job, or locally with MIROFY_CHROME set;
//   - any other row with a proof is SHIPPED.
// Rows the roadmap names that matrix.mjs does not yet carry are PLANNED --
// this is where every later P1b task's own row sits until its task lands,
// which is what keeps this file honest rather than aspirational.
//
// Run `npm run status` after any change to matrix.mjs (a task landing moves
// exactly one row from PLANNED to SHIPPED/UNPROVEN). `npm run status:check`
// (wired into `npm run check`, immediately after lint) regenerates into
// memory and diffs against the committed file, so a stale status file fails
// the build instead of quietly lying. That only proves this file agrees
// with matrix.mjs and the frozen ROADMAP_SNAPSHOT -- it says nothing about
// whether ROADMAP_SNAPSHOT itself still agrees with the live roadmap
// document. That is a separate, unavoidably-manual concern: run
// `npm run check:roadmap` (scripts/check-roadmap-snapshot.mjs) whenever the
// live roadmap might have changed; it is not part of `npm run check`
// because CI never checks out the sibling repo the live document lives in.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { HARVESTED_ROWS } from '../packages/conformance/src/matrix.mjs';
import { ROADMAP_SNAPSHOT } from './roadmap-snapshot.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..');
const OUT_PATH = path.join(repoRoot, 'docs/IMPLEMENTATION-STATUS.md');

const mdEscape = (value) => String(value)
  .replace(/\\/g, '\\\\')
  .replace(/\|/g, '\\|')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;');

function stateOf(row) {
  if (row.proof === null) return 'UNPROVEN';
  if (row.browser) return 'SHIPPED (browser-proved)';
  return 'SHIPPED';
}

const roadmapById = new Map(ROADMAP_SNAPSHOT.map(([id, name, origin, phase]) => [id, { name, origin, phase }]));
const matrixIds = new Set(HARVESTED_ROWS.map((row) => row.id));

function originOf(row) {
  return row.origin ?? roadmapById.get(row.id)?.origin ?? 'H';
}
function phaseOf(row) {
  return row.phase ?? roadmapById.get(row.id)?.phase ?? 'P0';
}

const shippedRows = HARVESTED_ROWS.filter((row) => row.proof !== null);
const browserProvedRows = shippedRows.filter((row) => row.browser);
const unprovenRows = HARVESTED_ROWS.filter((row) => row.proof === null);
const plannedRows = ROADMAP_SNAPSHOT.filter(([id]) => !matrixIds.has(id));

function render() {
  const lines = [];
  lines.push('# Implementation Status');
  lines.push('');
  lines.push('Generated by `node scripts/status.mjs` from `packages/conformance/src/matrix.mjs`');
  lines.push('(SHIPPED / UNPROVEN) and a committed snapshot of the roadmap,');
  lines.push('`analysis/future/32-PARITY-AND-FEATURE-MATRIX.md` (PLANNED -- rows the roadmap');
  lines.push('names that do not yet have a row of their own in the matrix).');
  lines.push('');
  lines.push('Do not hand-edit this file -- regenerate it with `npm run status`.');
  lines.push('`npm run status:check` (part of `npm run check`) fails the build if this file');
  lines.push('has drifted from what the matrix and the roadmap snapshot would produce.');
  lines.push('');
  lines.push('The PLANNED roadmap snapshot is a frozen, undated-by-revision copy (the sibling');
  lines.push('repo it comes from has no tracked history to pin to) -- it can go stale silently.');
  lines.push('Run `npm run check:roadmap` by hand to diff it against the live roadmap document.');
  lines.push('');
  lines.push(
    `**Totals:** ${shippedRows.length} SHIPPED (${browserProvedRows.length} browser-proved), `
    + `${unprovenRows.length} UNPROVEN, ${plannedRows.length} PLANNED.`,
  );
  lines.push('');
  lines.push('## Shipped & unproven — from the conformance matrix');
  lines.push('');
  lines.push('| ID | Name | Origin | Phase | State | Proof |');
  lines.push('|---|---|---|---|---|---|');
  for (const row of HARVESTED_ROWS) {
    const proof = row.proof === null ? `_none — ${mdEscape(row.note || 'no assertion exists')}_` : `\`${mdEscape(row.proof)}\``;
    lines.push(
      `| ${mdEscape(row.id)} | ${mdEscape(row.name)} | ${mdEscape(originOf(row))} | ${mdEscape(phaseOf(row))} `
      + `| ${stateOf(row)} | ${proof} |`,
    );
  }
  lines.push('');
  lines.push('## Planned — named in the roadmap, not yet in the matrix');
  lines.push('');
  lines.push('| ID | Name | Origin | Phase |');
  lines.push('|---|---|---|---|');
  for (const [id, name, origin, phase] of plannedRows) {
    lines.push(`| ${mdEscape(id)} | ${mdEscape(name)} | ${mdEscape(origin)} | ${mdEscape(phase)} |`);
  }
  lines.push('');
  return lines.join('\n');
}

const generated = render();

if (process.argv.includes('--check')) {
  let committed;
  try {
    committed = fs.readFileSync(OUT_PATH, 'utf8');
  } catch {
    console.error(`status:check: ${path.relative(repoRoot, OUT_PATH)} does not exist. Run \`npm run status\`.`);
    process.exit(1);
  }
  if (committed === generated) {
    console.log(`status:check: ${path.relative(repoRoot, OUT_PATH)} is up to date.`);
    process.exit(0);
  }
  console.error(`status:check: ${path.relative(repoRoot, OUT_PATH)} is stale -- committed content does not match what scripts/status.mjs would generate.`);
  const committedLines = committed.split('\n');
  const generatedLines = generated.split('\n');
  const limit = Math.max(committedLines.length, generatedLines.length);
  for (let i = 0; i < limit; i += 1) {
    if (committedLines[i] !== generatedLines[i]) {
      console.error(`  first difference at line ${i + 1}:`);
      console.error(`    committed:  ${JSON.stringify(committedLines[i] ?? '<eof>')}`);
      console.error(`    regenerated: ${JSON.stringify(generatedLines[i] ?? '<eof>')}`);
      break;
    }
  }
  console.error('Run `npm run status` to regenerate.');
  process.exit(1);
}

fs.writeFileSync(OUT_PATH, generated);
console.log(`status: wrote ${path.relative(repoRoot, OUT_PATH)} (${shippedRows.length} shipped, ${unprovenRows.length} unproven, ${plannedRows.length} planned)`);
